language: python
sudo: false
dist: bionic  # 18.04
if: (type = push AND branch IN (master)) OR (type = pull_request)
matrix:
  fast_finish: true
  include:

    - python: 3.10
      env: TOXENV=py310-flake8

    - python: 3.10
      env: TOXENV=py310-isort

    - python: 3.10
      env: TOXENV=py310-dj42
    - python: 3.11
      env: TOXENV=py311-dj42

    - python: 3.10
      env: TOXENV=py310-djmaster

  allow_failures:
    - python: 3.10
      env: TOXENV=py310-djmaster

cache:
  - apt
  - pip

install:
  - pip install tox
script:
  - tox
after_success:
  - pip install codecov
  - codecov

deploy:
  provider: pypi
  user: hellysmile
  password:
    secure: "MtYn/E/iO27Vhq8UNYjM7kcLUkKSG19ZVyysZAjoQQHaD7NE6Rc0nrQm6eG6n4LTy3IFKi79o9gDDwayFPSnId7gzGIxpF3tvnzfvM8za6a2tBJOl/J+x1anXwAyX4ifVmH3kkuLfpjch+ruAvU4+xex6U4IRiKg06yr3/DoJs8="
  distributions: sdist bdist_wheel
  on:
    tags: true
    all_branches: true
    python: 3.10
    condition: $TOXENV = py310-dj42

notifications:
  email:
    on_success: never
