language: python
sudo: false
dist: bionic  # 18.04
if: (type = push AND branch IN (master)) OR (type = pull_request)
matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TOXENV=py27-flake8
    - python: 3.6
      env: TOXENV=py36-flake8

    - python: 2.7
      env: TOXENV=py27-isort
    - python: 3.6
      env: TOXENV=py36-isort

    - python: 2.7
      env: TOXENV=py27-dj18
    - python: 3.3
      env: TOXENV=py33-dj18
    - python: 3.4
      env: TOXENV=py34-dj18
    - python: 3.5
      env: TOXENV=py35-dj18

    - python: 2.7
      env: TOXENV=py27-dj110
    - python: 3.4
      env: TOXENV=py34-dj110
    - python: 3.5
      env: TOXENV=py35-dj110

    - python: 2.7
      env: TOXENV=py27-dj111
    - python: 3.4
      env: TOXENV=py34-dj111
    - python: 3.5
      env: TOXENV=py35-dj111
    - python: 3.6
      env: TOXENV=py36-dj111

    - python: 3.4
      env: TOXENV=py34-dj20
    - python: 3.5
      env: TOXENV=py35-dj20
    - python: 3.6
      env: TOXENV=py36-dj20

    - python: 3.5
      env: TOXENV=py35-djmaster
    - python: 3.6
      env: TOXENV=py36-djmaster

  allow_failures:
    - python: 3.5
      env: TOXENV=py35-djmaster
    - python: 3.6
      env: TOXENV=py36-djmaster

cache: pip

install:
  - pip install tox
script:
  - tox
after_success:
  - pip install codecov
  - codecov

deploy:
  provider: pypi
  user: hellysmile
  password:
    secure: "MtYn/E/iO27Vhq8UNYjM7kcLUkKSG19ZVyysZAjoQQHaD7NE6Rc0nrQm6eG6n4LTy3IFKi79o9gDDwayFPSnId7gzGIxpF3tvnzfvM8za6a2tBJOl/J+x1anXwAyX4ifVmH3kkuLfpjch+ruAvU4+xex6U4IRiKg06yr3/DoJs8="
  distributions: sdist bdist_wheel
  on:
    tags: true
    all_branches: true
    python: 3.6
    condition: $TOXENV = py36-dj20

notifications:
  email:
    on_success: never
